fft-build: move the exit code check
Move the exit code check inside the loop since it only checks the last
return code.  The code will thus not work if the error happens on, say,
the second-to-last argument.

diff --git a/fft-build b/fft-build
--- a/fft-build
+++ b/fft-build
@@ -11,9 +11,8 @@
 for var in "$@"
 do
     ./fft-check-for-ff < "$var"
+    if [ $? -ne 0 ]; then
+        >&2 echo "fft-build: exiting due to aforementioned errors."
+        exit $?
+    fi
 done
-
-if [ $? -ne 0 ]; then
-    >&2 echo "fft-build: exiting due to aforementioned errors."
-    exit $?
-fi
